sudo: required
dist: trusty

language: c
compiler:
  - gcc
  - clang

env:
  - PLATFORM=posix TESTS=yes
  - PLATFORM=contiki
  - PLATFORM=lwip

addons:
  apt_packages:
    - pkg-config
    - graphviz
    - libcunit1-dev
    - doxygen
    - libxml2-utils
    - xsltproc
    - docbook-xml
    - asciidoc

# build only travis-test branch for now
branches:
  only:
     - travis-test

before_install: dpkg -l

before_script: ./autogen.sh --clean && ./autogen.sh && dpkg -l

script: scripts/build.sh
