sudo: required
dist: trusty

language: c
compiler:
  - gcc

env:
  - PLATFORM=posix TESTS=yes

addons:
  apt_packages:
    - pkg-config
    - graphviz
    - libcunit1-dev
    - doxygen
    - libxml2-utils
    - xsltproc
    - docbook-xml
    - docbook-xsl
    - docbook-dsssl
    - asciidoc
    - libxml-parser-perl
    - libxml-twig-perl
    - libxml-xpathengine-perl
    - dblatex
    - lynx
    - lynx-cur
    - sgmlspl
    - xorg-sgml-doctools
    - texlive

# build only travis-test branch for now
branches:
  only:
     - travis-test

before_script: dpkg -l && ./autogen.sh --clean && ./autogen.sh

script: scripts/build.sh
