sudo: required
dist: trusty

language: c
compiler:
  - gcc
  - clang

env:
  - PLATFORM=posix TESTS=yes
  - PLATFORM=contiki
  - PLATFORM=lwip

addons:
  apt_packages:
    - pkg-config
    - graphviz
    - libcunit1-dev
    - doxygen
    - libxml2-utils
    - xsltproc
    - docbook-xml
    - asciidoc
    - libxml-parser-perl
    - libxml-twig-perl
    - libxml-xpathengine-perl
    - dblatex
    - lynx
    - lynx-cur
    - sgmlspl
    - xorg-sgml-doctools

# build only travis-test branch for now
branches:
  only:
     - travis-test

before_script: ./autogen.sh --clean && ./autogen.sh

script: scripts/build.sh
